# SPDX-License-Identifier: MPL-2.0
# Copyright (C) 2020- The University of Tokyo
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import sys
import os
from importlib.util import find_spec
from setuptools import setup, Extension, find_packages
from setuptools.command.build_ext import build_ext


def debug_write(s):
    sys.stderr.write(f"DEBUG: {s}\n")


if find_spec("Cython") is not None:
    cython_installed = True
else:
    cython_installed = False

physbo_disable_cython = os.environ.get("PHYSBO_DISABLE_CYTHON", "0")

if physbo_disable_cython == "1":
    USE_CYTHON = False
else:
    USE_CYTHON = cython_installed

debug_write(f"{cython_installed=}")
debug_write(f"{physbo_disable_cython=}")
debug_write(f"{USE_CYTHON=}")

if USE_CYTHON:
    from Cython.Build import cythonize

    import numpy

    compile_flags = [
        "-O3",
    ]
    ext_mods = cythonize(
        [
            Extension(
                name="physbo.misc._src.cythononized",
                sources=["src/physbo/misc/_src/cythonized.pyx"],
                include_dirs=[numpy.get_include()],
                extra_compile_args=compile_flags,
            ),
            Extension(
                name="physbo.gp.cov._src.enhance_gauss",
                sources=["src/physbo/gp/cov/_src/enhance_gauss.pyx"],
                include_dirs=[numpy.get_include()],
                extra_compile_args=compile_flags,
            ),
        ]
    )
else:
    ext_mods = []


class CythonBuildExt(build_ext):
    def run(self):
        sys.stderr.write(f"DEBUG: build_lib: {self.build_lib}\n")
        with open(os.path.join(self.build_lib, "physbo", "_build_info.py"), "a") as f:
            f.write(
                f"USING_CYTHON = {USE_CYTHON} # this line is generated by setup.py\n"
            )
        super().run()


setup(
    package_dir={"physbo": "src/physbo"},
    packages=find_packages(where="src"),
    cmdclass={"build_ext": CythonBuildExt},
    ext_modules=ext_mods,
    name="physbo",
)
