name: Build and deploy documentation

# Build documentation for all branches and tags for purpose of testing.
# Deploy documentation to gh-pages only for master and develop branches, and tags.

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        uv sync --extra docs
    - name: Build docs
      run: |
        sh ${{ github.workspace }}/docs/make_docs.sh

    - name: Upload built docs for deployment
      uses: actions/upload-artifact@v4
      if: github.ref_name == 'master' || github.ref_name == 'develop' || github.ref_type == 'tag'
      with:
        name: docs-${{ github.ref_name }}
        path: ${{ github.workspace }}/docs/built
        retention-days: 1

  deploy:
    if: github.ref_name == 'master' || github.ref_name == 'develop' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: Download built docs
      uses: actions/download-artifact@v4
      with:
        name: docs-${{ github.ref_name }}
        path: ${{ github.workspace }}/built-docs

    - name: Deploy Configuration
      run: |
          mkdir ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

    - name: Push
      env:
        GIT_USER: "PHYSBO Developers"
        GIT_EMAIL: "physbo-dev@issp.u-tokyo.ac.jp"
        TARGET_NAME: ${{ github.ref_name }}
      run: |
          cd ${GITHUB_WORKSPACE}
          for lang in ja en; do
            rm -rf "gh-pages/manual/${TARGET_NAME}/${lang}"
            mkdir -p "gh-pages/manual/${TARGET_NAME}"
            cp -r "built-docs/manual/${lang}" "gh-pages/manual/${TARGET_NAME}/"
          done
          cd gh-pages
          git config --local user.name "${GIT_USER}"
          git config --local user.email "${GIT_EMAIL}"
          git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
          git add manual
          if git commit -m "Deploy docs to ${TARGET_NAME} by GitHub Actions triggered by ${GITHUB_SHA}"
          then
            git push origin gh-pages
          else
            echo "Nothing to deploy"
          fi
