name: Test python package

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 AM, 1st and 15th of every month

jobs:
  build:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} with NumPy ${{ matrix.numpy-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        numpy-version: ['latest']
        include:
          - os: 'macos-latest'
            python-version: '3.9'
            numpy-version: 'latest'
          - os: 'macos-latest'
            python-version: '3.13'
            numpy-version: 'latest'
          - os: 'windows-latest'
            python-version: '3.9'
            numpy-version: 'latest'
          - os: 'windows-latest'
            python-version: '3.13'
            numpy-version: 'latest'
          - os: 'ubuntu-latest'
            python-version: '3.9'
            numpy-version: '1.26.4'
          - os: 'ubuntu-latest'
            python-version: '3.13'
            numpy-version: '1.26.4'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run:  uv sync --extra tests
    - name: Install NumPy 1.26.4
      if: matrix.numpy-version == '1.26.4'
      run: uv pip install "numpy==1.26.4"
    - name: PyTest
      run: uv run pytest --capture=sys --cov=physbo --cov-report=term tests

  mpi:
    name: MPI tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Set up UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.13'
    - name: Install OpenMPI
      run: |
        sudo apt update
        sudo apt install -y libopenmpi-dev openmpi-bin
    - name: Install dependencies
      run: uv sync --extra tests --extra mpi
    - name: PyTest (MPI)
      run: uv run pytest tests/mpi -v
